name: Deploy to Server

on:
  push:
    branches:
      - main  # Trigger this workflow only on pushes to the 'main' branch
  workflow_dispatch:  # Allow manual triggering of this workflow

jobs:
  deploy:
    runs-on: ubuntu-latest  # GitHub runner (virtual machine)

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Add Host Key to Known Hosts
      - name: Set Up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts

      # Step 3: Deploy files to the server and prepare directory
      - name: Deploy Files and Prepare Directory
        uses: easingthemes/ssh-deploy
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: "."
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: "/var/www/html"
          SCRIPT_BEFORE: |
            sudo chown -R ubuntu:ubuntu /var/www/html
          SCRIPT_AFTER: |
            mv /var/www/html/.env.example /var/www/html/.env

    
