name: Deploy to Server

on:
  push:
    branches:
      - main   # Trigger this workflow only on pushes to the 'main' branch
  workflow_dispatch:   # Allow manual triggering of this workflow

jobs:
  deploy:
    runs-on: ubuntu-latest  # GitHub runner (virtual machine)

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Deploy files and prepare directory
      - name: Deploy Files and Prepare Directory
        uses: easingthemes/ssh-deploy@v5.1.0
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          SOURCE: "."
          TARGET: "/var/www/html"
          SCRIPT_BEFORE: |
            sudo chown -R ubuntu:ubuntu /var/www/html
          SCRIPT_AFTER: |
            mv /var/www/html/.env.example /var/www/html/.env
